[profile.default]
src = "contracts"
test = "test"
out = "forge-out"
libs = []
solc = ".tools/solc-0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
via_ir = false
fs_permissions = []
